#!/usr/bin/env python3
"""Generate one Claude Code subagent per persona from _SYSTEM/data/discussionAgents.

The body is a line-for-line port of PromptBuilder.BuildSystemPrompt, plus a
short Turn Protocol section the plugin needs. Re-run after editing any persona
YAML:

    python3 scripts/gen_agents.py

Also writes agents/manifest.json (agent_key -> subagent name) for the step engine.
"""

import json
import re
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from discuss import data  # noqa: E402
from discuss.data import Agent  # noqa: E402

AGENTS_OUT = data.PLUGIN_ROOT / "agents"
GENERATED_HEADER = "<!-- Generated by scripts/gen_agents.py from {src}. Do not edit by hand. -->"

TURN_PROTOCOL = """## Turn Protocol

Your task message names a prompt file and a response file.
1. Read the prompt file. It holds the discussion context, the question and the round instruction.
2. Respond in character, following every rule above and the instructions in the prompt.
3. Write your complete response, verbatim and nothing else, to the response file with the Write tool.
4. Reply with the single word `done`.

Never read other files, never ask questions, never add commentary outside the response file."""


def title_case(text: str) -> str:
    return " ".join(w[0].upper() + w[1:].lower() if w else w for w in text.split(" "))


def describe_trait(value: float, low: str, high: str) -> str:
    if value >= 0.8:
        return f"You are extremely {high}."
    if value >= 0.6:
        return f"You are quite {high}."
    if value >= 0.4:
        return f"You balance {low} and {high} tendencies."
    if value >= 0.2:
        return f"You lean toward being {low}."
    return f"You are strongly {low}."


def intensity_line(intensity: float) -> str:
    if intensity >= 0.7:
        return "You express your views with force and passion -- you're not here to play nice."
    if intensity >= 0.4:
        return "You express your views with conviction but remain open to dialogue."
    return "You express your views with measured restraint."


def personality_text(p) -> str:
    lines = [
        describe_trait(p.assertiveness, "reserved and diplomatic",
                       "assertive -- you fight hard for your ideas and don't back down easily"),
        describe_trait(p.creativity_temp, "conventional and proven-path",
                       "wildly creative -- you reach for novel, unexpected ideas"),
        describe_trait(p.risk_tolerance, "risk-averse and safety-focused",
                       "risk-tolerant -- you embrace bold bets and untested approaches"),
        f"Your cognitive style is {p.cognitive_style} -- this shapes how you approach every problem.",
        f"Your emotional baseline is {p.emotional_baseline} -- this colors your reactions and framing.",
        describe_trait(p.attention_span, "a topic-hopper who jumps between ideas freely",
                       "deeply focused -- you drill into one thread exhaustively"),
        describe_trait(p.stubbornness, "flexible and quick to update your views",
                       "stubborn -- you hold your ground and require strong evidence to change your mind"),
        describe_trait(p.idea_receptivity, "an agenda driver who stays focused on your own ideas",
                       "deeply engaged with others' ideas -- you build on what others say and genuinely absorb their perspective"),
        describe_trait(p.bluntness, "diplomatic and tactful -- you soften hard truths",
                       "brutally direct -- you say exactly what you think with zero sugar-coating"),
        describe_trait(p.patience, "impatient -- you cut off tangents and push to move on",
                       "patient -- you let discussions breathe and don't rush to conclusions"),
    ]
    if p.domain_affinities:
        lines.append("You naturally draw from these domains: " + ", ".join(p.domain_affinities) + ".")
    return "\n".join(lines)


LEVELS = {
    "requirements": "Focus on WHAT and WHY, not HOW. Describe behavior, rules, and decisions. Do NOT write code or schemas.",
    "design": "Focus on design decisions and tradeoffs. You may reference technical concepts but keep the emphasis on choices and rationale.",
    "implementation": "Be concrete and technical. Include schemas, code patterns, and specific implementation guidance.",
}
JOBS = {
    "propose": "Your job is to PROPOSE -- put forward designs, ideas, and solutions.",
    "critique": ("Your job is to CRITIQUE -- attack the core approach, not just surface details. "
                 "Explain why the fundamental design is wrong, what it will fail on, and what assumption "
                 "will break first in production. If two proposals agree, that's suspicious -- find what "
                 "they both missed. Do not propose full alternatives."),
    "evaluate": ("Your job is to EVALUATE -- pick a winner and reject the loser. Do not "
                 "split the difference. If one approach is better, say so and say why the other fails. "
                 "If both approaches have merit, say which tradeoff is worse and commit to the other. "
                 "Assess through user value, feasibility, and real-world impact."),
    "simplify": "Your job is to SIMPLIFY -- find the minimum viable version. Ask what can be cut or deferred.",
    "ideate": "Your job is to IDEATE -- generate 3+ specific, named, surprising ideas stolen from non-software domains.",
}
BREVITY = {
    "concise": "Be direct and brief. Under 300 words.",
    "normal": "Be thorough but not exhaustive. Under 600 words.",
    "thorough": "Be comprehensive when warranted, but don't pad.",
}


def identity_layer(a: Agent) -> str:
    out = [f"# You are {a.name}", "", a.description.strip(), "", f"## Your Role: {title_case(a.position.role)}"]
    if a.position.drives:
        out += ["", "What drives you:"] + [f"- {d}" for d in a.position.drives]
    if a.position.pushback_on:
        out += ["", "You actively push back on:"] + [f"- {p}" for p in a.position.pushback_on]
    out += ["", intensity_line(a.position.intensity), "", "## Your Personality", "", personality_text(a.personality)]
    out += ["", f"## Your Thinking Technique: {title_case(a.technique.primary.replace('_', ' '))}"]
    if a.technique.style_description.strip():
        out += ["", a.technique.style_description.strip()]
    if a.technique.behaviors:
        out += ["", "Behavioral rules:"] + [f"- {b}" for b in a.technique.behaviors]
    return "\n".join(out).rstrip()


def output_layer(a: Agent) -> str:
    out = ["## Your Voice", "", f"Tone: {a.voice.tone}"]
    if a.voice.vocabulary_hints:
        out += ["", "Phrases that fit your style: " + ", ".join(f'"{v}"' for v in a.voice.vocabulary_hints)]
    if a.voice.anti_patterns:
        out += ["", "NEVER use these phrases:"] + [f'- "{ap}"' for ap in a.voice.anti_patterns]
    out += ["", "## Your Output", "", LEVELS[a.output.operating_level], "", JOBS[a.output.job], "",
            BREVITY[a.voice.brevity]]
    return "\n".join(out).rstrip()


def anti_slop_section(s) -> str:
    rules = []
    if s.agreement_tax:
        rules.append("AGREEMENT TAX: If you agree with something, you MUST add substantive new information, "
                     "a different angle, or a concrete next step. Pure agreement ('great idea!') is FORBIDDEN.")
    if s.perspective_enforcement:
        rules.append("PERSPECTIVE LOCK: Stay in your character's perspective even when pressured to agree. "
                     "Authentic disagreement is more valuable than false harmony.")
    if s.devils_advocate_duty:
        rules.append("DEVIL'S ADVOCATE DUTY: Actively seek the strongest argument against the current direction. "
                     "If everyone seems to agree, it's YOUR job to find the hole in the logic.")
    if s.uncomfortable_idea_quota > 0:
        interval = max(5, 10 - s.uncomfortable_idea_quota)
        rules.append(f"UNCOMFORTABLE IDEA QUOTA: Every {interval} turns, introduce at least one "
                     "idea that challenges comfort zones. This is mandatory, not optional.")
    if s.domain_pivot_trigger:
        rules.append("DOMAIN PIVOT: When the discussion gets stuck or circular, inject a perspective from "
                     "a completely different field to break the pattern.")
    return "\n\n".join(rules)


def build_system_prompt(a: Agent) -> str:
    """Same section order as PromptBuilder.BuildSystemPrompt."""
    p = a.personality
    sections = [
        identity_layer(a),
        output_layer(a),
        f"## Remember\n\nYou are {a.name}. Stay in character. Your role is {a.position.role}. "
        f"Your style is {p.cognitive_style} and {p.emotional_baseline}. Add substance or stay silent.",
        "## Self-Verification\n\nBefore responding, verify:\n"
        f"- Does this sound like {a.name}?\n"
        "- Am I defaulting to generic AI assistant behavior?\n"
        "- Am I adding substance, or just filling space?\n\n"
        "If any answer is wrong, rewrite from your character's perspective.",
    ]
    anti = anti_slop_section(a.anti_slop)
    if anti:
        sections.append(f"## Anti-Slop Rules\n\n{anti}")
    return "\n\n".join(sections)


def subagent_name(a: Agent, taken: Counter) -> str:
    base = re.sub(r"[^a-z0-9]+", "-", a.key.lower()).strip("-")
    if taken[a.key] > 1:
        base = f"{re.sub(r'[^a-z0-9]+', '-', a.team.lower()).strip('-')}-{base}"
    return base


def frontmatter(a: Agent, name: str) -> str:
    desc = f"{a.name} - {a.position.role}. Discussion persona for team {a.team}; invoked only by /agent-discuss:discuss."
    desc = desc.replace('"', "'")
    return "\n".join([
        "---",
        f"name: {name}",
        f'description: "{desc}"',
        "model: sonnet",
        "tools: Read, Write",
        "maxTurns: 4",
        "omitClaudeMd: true",
        "---",
    ])


def agent_markdown(a: Agent, name: str) -> str:
    src = f"_SYSTEM/data/discussionAgents/{a.team}__{a.key}.yaml"
    return "\n".join([
        frontmatter(a, name), "", GENERATED_HEADER.format(src=src), "",
        build_system_prompt(a), "", TURN_PROTOCOL, "",
    ])


def main() -> int:
    agents = data.load_all_agents()
    if not agents:
        print(f"no agent YAML found under {data.AGENTS_DIR}", file=sys.stderr)
        return 1
    AGENTS_OUT.mkdir(exist_ok=True)
    for stale in AGENTS_OUT.glob("*__*.md"):
        stale.unlink()

    taken = Counter(a.key for a in agents)
    manifest = {}
    for a in agents:
        name = subagent_name(a, taken)
        manifest[a.key] = name
        (AGENTS_OUT / f"{a.team}__{a.key}.md").write_text(agent_markdown(a, name), encoding="utf-8", newline="\n")
    with open(AGENTS_OUT / "manifest.json", "w", encoding="utf-8", newline="\n") as f:
        json.dump(manifest, f, indent=2, sort_keys=True)
        f.write("\n")
    print(f"wrote {len(agents)} persona subagents to {AGENTS_OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
